import type { AiAdapter, AiRequest } from './types'

/**
 * Demo adapter: deterministic, offline "AI" for demos and automated tests. It never
 * calls a model — replace it with an adapter that calls your backend.
 */
export function createDemoAiAdapter(options: { delayMs?: number; chunkSize?: number } = {}): AiAdapter {
  const delayMs = options.delayMs ?? 15
  const chunkSize = options.chunkSize ?? 16
  return {
    async complete(request, { signal, onChunk }) {
      const output = demoResponse(request)
      for (let i = 0; i < output.length; i += chunkSize) {
        if (signal.aborted) throw new DOMException('Aborted', 'AbortError')
        onChunk(output.slice(i, i + chunkSize))
        if (delayMs) await new Promise((r) => setTimeout(r, delayMs))
      }
      if (signal.aborted) throw new DOMException('Aborted', 'AbortError')
      return output
    },
  }
}

// Split after . ! ? followed by whitespace, so dots inside URLs and numbers don't split.
const sentences = (text: string) => text.split(/(?<=[.!?])\s+/).map((s) => s.trim()).filter(Boolean)
const has = (instruction: string, ...words: string[]) => words.some((w) => instruction.toLowerCase().includes(w))

const FORMAL: [RegExp, string][] = [
  [/\bcan't\b/gi, 'cannot'], [/\bdon't\b/gi, 'do not'], [/\bwon't\b/gi, 'will not'], [/\bit's\b/gi, 'it is'],
  [/\bisn't\b/gi, 'is not'], [/\bwe're\b/gi, 'we are'], [/\bgreat\b/gi, 'excellent'], [/\bget\b/gi, 'obtain'],
  [/\ba lot of\b/gi, 'a considerable amount of'], [/\bbig\b/gi, 'significant'],
]

/** Exported for tests. */
export function demoResponse(request: AiRequest): string {
  const instruction = request.instruction ?? ''
  switch (request.task) {
    case 'edit-selection':
      return editText(request.selection ?? '', instruction)
    case 'continue':
      return 'Building on this, the next step is to confirm owners and timelines so the plan can move forward without delays.'
    case 'generate': {
      const topic = instruction.replace(/^(write|create|draft|generate)\s+(an?\s+)?/i, '').replace(/[.!]+$/, '') || 'New document'
      const title = topic.charAt(0).toUpperCase() + topic.slice(1)
      return `# ${title}\n\nThis draft was generated by the demo AI adapter. Replace it with a Gemini-backed adapter to get real content.\n\n## Key points\n\n- Goal and scope of the work\n- Current status and risks\n- Next steps and owners\n\n## Status\n\n| Area | Status | Owner |\n| --- | --- | --- |\n| Planning | Done | Alex |\n| Delivery | In progress | Sam |\n`
    }
    case 'chat':
      return demoChat(request)
    case 'edit-document': {
      // Only plain paragraphs are touched, and at most three: shows that untouched blocks stay as they are.
      const edits = (request.blocks ?? [])
        .filter((b) => /^[A-Za-z*_]/.test(b.markdown) && /[a-z]{3}/i.test(b.markdown))
        .slice(0, 3)
        .map((b) => {
          const edited = editText(b.markdown, instruction)
          // Always show a visible change in the demo, even when the rule found nothing to edit.
          return { id: b.id, markdown: edited === b.markdown ? `${b.markdown} (revised)` : edited }
        })
      return JSON.stringify({ edits })
    }
  }
}

function editText(text: string, instruction: string): string {
  const clean = text.trim()
  if (has(instruction, 'table')) {
    const rows = sentences(clean.replace(/^[-*]\s+/gm, '')).slice(0, 6)
    return `| # | Point |\n| --- | --- |\n${rows.map((r, i) => `| ${i + 1} | ${r.replace(/\|/g, '/')} |`).join('\n')}`
  }
  if (has(instruction, 'list', 'bullet')) return sentences(clean).map((s) => `- ${s}`).join('\n')
  if (has(instruction, 'short', 'concise')) return sentences(clean)[0]
  if (has(instruction, 'summar')) return `In short: ${sentences(clean)[0]}`
  if (has(instruction, 'longer', 'expand', 'detail')) return `${clean} This point matters because it affects the timeline, the budget and the people involved.`
  if (has(instruction, 'formal', 'professional')) {
    // Keep the capital letter when the replaced word started a sentence.
    return FORMAL.reduce((t, [re, to]) => t.replace(re, (m) => (m[0] === m[0].toUpperCase() ? to[0].toUpperCase() + to.slice(1) : to)), clean)
  }
  if (has(instruction, 'casual', 'friendly')) return `${clean.replace(/\bcannot\b/gi, "can't").replace(/\bdo not\b/gi, "don't")} 🙂`
  if (has(instruction, 'translate')) return `[Translated] ${clean}`
  if (has(instruction, 'grammar', 'spelling')) {
    return clean.replace(/\s{2,}/g, ' ').replace(/\bi\b/g, 'I').replace(/(^|[.!?]\s+)([a-z])/g, (_m, p, c) => p + c.toUpperCase())
  }
  return `${clean.replace(/\bvery\s+/gi, '').replace(/\breally\s+/gi, '')} (revised)`
}

const STOP_WORDS = new Set(['the', 'a', 'an', 'is', 'are', 'what', 'who', 'which', 'of', 'in', 'on', 'to', 'and', 'or', 'for', 'does', 'do', 'this', 'that', 'it', 'about', 'me', 'tell', 'document', 'there', 'how', 'why', 'when', 'where'])
const plain = (markdown: string) =>
  markdown.replace(/==/g, '').replace(/[#*_`>|[\]()!-]/g, ' ').replace(/\s+/g, ' ').replace(/\s+([.,;:!?])/g, '$1').trim()

/** Deterministic chat answers that cite blocks, for demos and tests. */
function demoChat(request: AiRequest): string {
  const question = request.instruction.toLowerCase()
  const blocks = request.blocks ?? []
  const paragraphs = blocks.filter((b) => /^[A-Za-z*_]/.test(b.markdown) && /[a-z]{3}/i.test(b.markdown))
  const lists = blocks.filter((b) => /^(\d+\.|[-*+])\s/.test(b.markdown))

  if (has(question, 'change', 'rewrite', 'make ', 'formal', 'shorten', 'fix')) {
    const target = paragraphs[0]
    if (!target) return "There's no paragraph I could change."
    const edited = editText(target.markdown, question)
    const edits = [{ id: target.id, markdown: edited === target.markdown.trim() ? `${edited} (revised)` : edited }]
    return `I rewrote the opening paragraph [${target.id}]. Review the suggested change in the document.\n\n\`\`\`edits\n${JSON.stringify({ edits })}\n\`\`\``
  }
  if (has(question, 'summar', 'overview', 'tl;dr')) {
    if (!paragraphs.length) return 'The document has no text to summarize yet.'
    return `Summary:\n\n${paragraphs
      .slice(0, 3)
      .map((b) => `- ${sentences(plain(b.markdown))[0]} [${b.id}]`)
      .join('\n')}`
  }
  if (has(question, 'action', 'next step', 'todo', 'to-do', 'task')) {
    if (!lists.length) return "I couldn't find any action items in the document."
    const items = lists.flatMap((b) =>
      b.markdown
        .split('\n')
        .filter((line) => /^\s*(\d+\.|[-*+])\s/.test(line))
        .map((line) => `- ${plain(line.replace(/^\s*(\d+\.|[-*+])\s(\[[ x]\]\s)?/, ''))} [${b.id}]`),
    )
    return `Action items in the document:\n\n${items.slice(0, 8).join('\n')}`
  }

  // A question about a selected passage: answer from the block that contains it.
  if (request.selection) {
    const probe = plain(request.selection).slice(0, 30).toLowerCase()
    const source = blocks.find((b) => plain(b.markdown).toLowerCase().includes(probe))
    if (source) return `About the selected text: "${sentences(plain(request.selection))[0]}" [${source.id}]`
  }

  // Otherwise: quote the block that shares the most words with the question.
  const words = question.match(/[a-z0-9]{3,}/g)?.filter((w) => !STOP_WORDS.has(w)) ?? []
  let best: { id: string; markdown: string } | undefined
  let bestScore = 0
  for (const b of blocks) {
    const text = b.markdown.toLowerCase()
    const score = words.filter((w) => text.includes(w)).length
    if (score > bestScore) {
      best = b
      bestScore = score
    }
  }
  if (!best) return "I couldn't find that in the document."
  const quote = sentences(plain(best.markdown)).reduce(
    (top, s) => {
      const score = words.filter((w) => s.toLowerCase().includes(w)).length
      return score > top.score ? { s, score } : top
    },
    { s: '', score: 0 },
  ).s
  return `The document says: "${quote}" [${best.id}]`
}
